### ISSUE TITLE
ios 12.4.3  iphone5s dpkg install error

### ISSUE THREAD

**Issue by wbteve** [rockqj/networkfixer#1]
Selecting previously unselected package com.rockqj.networkfixer.
(Reading database ... 1702 files and directories currently installed.)
Preparing to unpack com.rockqj.networkfixer_1.0.0-1_iphoneos-arm.deb ...
Unpacking com.rockqj.networkfixer (1.0.0-1) ...
Setting up com.rockqj.networkfixer (1.0.0-1) ...
Load framework failed.
dpkg: error processing package com.rockqj.networkfixer (--install):
 installed com.rockqj.networkfixer package post-installation script subprocess returned error exit status 255
Errors were encountered while processing:
 com.rockqj.networkfixer

**Comment by rockqj** [comment]
The tool was made for iOS 13 initially. It didn't work in iOS 12 due to different framework name.
After this change dcb9d91f5090c12c73fd8509660091924d461879, it should work in iOS 12.

https://github.com/rockqj/networkfixer/blob/master/packages/com.rockqj.networkfixer_1.0.0-2_iphoneos-arm.deb

The code change is minor but I don't have device to test it..

**Comment by wbteve** [comment]
cd /var/preferences  &&  rm  com.apple.networkextension.necp.plist   com.apple.networkextension.plist   com.apple.networkextension.uuidcache.plist  &&  killall CommCenter  &&  killall backboardd

**Comment by wbteve** [comment]
开始以为是激活电话功能，如果是网络权限的，命令行删除更好用
